// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Genre struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Image     string    `json:"image"`
	CreatedAt time.Time `json:"created_at"`
}

type Playlist struct {
	ID        int64     `json:"id"`
	UsersID   int64     `json:"users_id"`
	Name      string    `json:"name"`
	Image     string    `json:"image"`
	CreatedAt time.Time `json:"created_at"`
}

type PlaylistsSong struct {
	ID          int64 `json:"id"`
	SongsID     int64 `json:"songs_id"`
	PlaylistsID int64 `json:"playlists_id"`
}

type Song struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Singer    string    `json:"singer"`
	Image     string    `json:"image"`
	FileUrl   string    `json:"file_url"`
	Duration  time.Time `json:"duration"`
	CreatedAt time.Time `json:"created_at"`
}

type SongsGenre struct {
	ID       int64 `json:"id"`
	SongsID  int64 `json:"songs_id"`
	GenresID int64 `json:"genres_id"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	FullName  string    `json:"full_name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Image     string    `json:"image"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}
