// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	AddSongToPlaylist(ctx context.Context, arg AddSongToPlaylistParams) (PlaylistsSong, error)
	CreateGenre(ctx context.Context, arg CreateGenreParams) (Genre, error)
	CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error)
	CreatePlaylistSong(ctx context.Context, arg CreatePlaylistSongParams) (PlaylistsSong, error)
	CreateSong(ctx context.Context, arg CreateSongParams) (Song, error)
	CreateSongGenre(ctx context.Context, arg CreateSongGenreParams) (SongsGenre, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteGenre(ctx context.Context, id int64) error
	DeletePlaylist(ctx context.Context, id int64) error
	DeletePlaylistSong(ctx context.Context, id int64) error
	DeleteSong(ctx context.Context, id int64) error
	DeleteSongGenre(ctx context.Context, arg DeleteSongGenreParams) error
	DeleteUser(ctx context.Context, id int64) error
	GetGenre(ctx context.Context, id int64) (Genre, error)
	GetGenreSongs(ctx context.Context, genresID int64) ([]Song, error)
	GetGenres(ctx context.Context, arg GetGenresParams) ([]Genre, error)
	GetPlaylistSong(ctx context.Context, id int64) (PlaylistsSong, error)
	GetPlaylistSongWithOffset(ctx context.Context, arg GetPlaylistSongWithOffsetParams) (Song, error)
	GetRandomPlaylistSong(ctx context.Context, arg GetRandomPlaylistSongParams) (Song, error)
	GetRandomSong(ctx context.Context, id int64) (Song, error)
	GetSong(ctx context.Context, id int64) (Song, error)
	GetSongGenre(ctx context.Context, id int64) (SongsGenre, error)
	GetSongWithOffset(ctx context.Context, offset int32) (Song, error)
	GetSongs(ctx context.Context, arg GetSongsParams) ([]Song, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserPlaylist(ctx context.Context, id int64) (Playlist, error)
	GetUserPlaylistSongs(ctx context.Context, playlistsID int64) ([]Song, error)
	GetUserPlaylists(ctx context.Context, usersID int64) ([]Playlist, error)
	ListPlaylistsSongs(ctx context.Context, arg ListPlaylistsSongsParams) ([]PlaylistsSong, error)
	ListSongsGenres(ctx context.Context, songsID int64) ([]int64, error)
	ListUsers(ctx context.Context) ([]User, error)
	RemoveSongFromPlaylist(ctx context.Context, arg RemoveSongFromPlaylistParams) error
	UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error)
	UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error)
	UpdateSongFile(ctx context.Context, arg UpdateSongFileParams) (Song, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	Updategenre(ctx context.Context, arg UpdategenreParams) (Genre, error)
}

var _ Querier = (*Queries)(nil)
