// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: songs.sql

package db

import (
	"context"
)

const createSong = `-- name: CreateSong :one
INSERT INTO songs (
  name,
  singer,
  image,
  file_url,
  duration
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, name, singer, image, file_url, duration, created_at
`

type CreateSongParams struct {
	Name     string `json:"name"`
	Singer   string `json:"singer"`
	Image    string `json:"image"`
	FileUrl  string `json:"file_url"`
	Duration int64  `json:"duration"`
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRowContext(ctx, createSong,
		arg.Name,
		arg.Singer,
		arg.Image,
		arg.FileUrl,
		arg.Duration,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Singer,
		&i.Image,
		&i.FileUrl,
		&i.Duration,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSong = `-- name: DeleteSong :exec
DELETE FROM songs
WHERE id = $1
`

func (q *Queries) DeleteSong(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSong, id)
	return err
}

const getRandomSong = `-- name: GetRandomSong :one
SELECT id, name, singer, image, file_url, duration, created_at FROM songs s WHERE s.id != $1 ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) GetRandomSong(ctx context.Context, id int64) (Song, error) {
	row := q.db.QueryRowContext(ctx, getRandomSong, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Singer,
		&i.Image,
		&i.FileUrl,
		&i.Duration,
		&i.CreatedAt,
	)
	return i, err
}

const getSong = `-- name: GetSong :one
SELECT id, name, singer, image, file_url, duration, created_at FROM songs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSong(ctx context.Context, id int64) (Song, error) {
	row := q.db.QueryRowContext(ctx, getSong, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Singer,
		&i.Image,
		&i.FileUrl,
		&i.Duration,
		&i.CreatedAt,
	)
	return i, err
}

const getSongWithOffset = `-- name: GetSongWithOffset :one
SELECT id, name, singer, image, file_url, duration, created_at FROM songs
ORDER BY id
LIMIT 1
OFFSET $1
`

func (q *Queries) GetSongWithOffset(ctx context.Context, offset int32) (Song, error) {
	row := q.db.QueryRowContext(ctx, getSongWithOffset, offset)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Singer,
		&i.Image,
		&i.FileUrl,
		&i.Duration,
		&i.CreatedAt,
	)
	return i, err
}

const getSongs = `-- name: GetSongs :many
SELECT id, name, singer, image, file_url, duration, created_at FROM songs
ORDER BY id
LIMIT $1
OFFSET $2
`

type GetSongsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetSongs(ctx context.Context, arg GetSongsParams) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, getSongs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Song{}
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Singer,
			&i.Image,
			&i.FileUrl,
			&i.Duration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSong = `-- name: UpdateSong :one
UPDATE songs
SET name = COALESCE($2, name),
    singer = COALESCE($3, singer),
    image = COALESCE($4, image),
    file_url = COALESCE($5, file_url),
    duration = COALESCE($6, duration)
WHERE id = $1
RETURNING id, name, singer, image, file_url, duration, created_at
`

type UpdateSongParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Singer   string `json:"singer"`
	Image    string `json:"image"`
	FileUrl  string `json:"file_url"`
	Duration int64  `json:"duration"`
}

func (q *Queries) UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error) {
	row := q.db.QueryRowContext(ctx, updateSong,
		arg.ID,
		arg.Name,
		arg.Singer,
		arg.Image,
		arg.FileUrl,
		arg.Duration,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Singer,
		&i.Image,
		&i.FileUrl,
		&i.Duration,
		&i.CreatedAt,
	)
	return i, err
}

const updateSongFile = `-- name: UpdateSongFile :one
UPDATE songs
SET file_url = $2,
    image = $3
WHERE id = $1
RETURNING id, name, singer, image, file_url, duration, created_at
`

type UpdateSongFileParams struct {
	ID      int64  `json:"id"`
	FileUrl string `json:"file_url"`
	Image   string `json:"image"`
}

func (q *Queries) UpdateSongFile(ctx context.Context, arg UpdateSongFileParams) (Song, error) {
	row := q.db.QueryRowContext(ctx, updateSongFile, arg.ID, arg.FileUrl, arg.Image)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Singer,
		&i.Image,
		&i.FileUrl,
		&i.Duration,
		&i.CreatedAt,
	)
	return i, err
}
