package db

import (
	"context"
	"database/sql"
	"fmt"
)

// Store provide all functions to execute SQL queries and transactions
type Store interface {
	// Querier is an interface generated by sqlc to define all function signatures of Queries struct
	Querier
}

// SQLStore provide all functions to execute SQL queries and transactions
type SQLStore struct {
	*Queries
	db *sql.DB
}

// NewStore creates a new store
func NewStore(db *sql.DB) Store {
	return &SQLStore{
		db:      db,
		Queries: New(db),
	}
}

// execTx execute function within a database transaction - lowerCase first
// mean we dont want external package to call it directly
func (store *SQLStore) execTx(ctx context.Context, fn func(*Queries) error) error {
	tx, err := store.db.BeginTx(ctx, nil)

	if err != nil {
		return err
	}

	q := New(tx)
	err = fn(q)

	if err != nil {
		if rbErr := tx.Rollback(); rbErr != nil {
			return fmt.Errorf("tx err: %v, rb err: %v", err, rbErr)
		}

		return err
	}

	return tx.Commit()
}
